version: '3'
services:
  server:
    build:
      context: .
      dockerfile: './dockerfile/Dockerfile'
    ports:
      - '3000:3000'
    volumes:
      - .:/app/
    entrypoint: [ "bundle", "exec", "rails", "s", "-b", "0.0.0.0" ]
    links:
      - database
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: challenge_walk
    expose:
      - '5432'
