# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9efefb105483bd5e74c0418cd22b5dcd73b1d8830db45cb504848c43ba90cf1e2650c65298ce9dfdedf9554ab5bb6db9fa8160f8a5e9f739e160512db1c30b59

test:
  secret_key_base: c04b2bbd2513f4ba0e98428459d23e78e07345b691dbbe9976be903d95ad491aa54f3883534782149b09778edb43a690a417841a3281cd60fc4a92b99889ca26

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
